apiVersion: apps/v1
kind: Deployment
metadata:
  name: contributor-management-service
  labels:
    app: contributor-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contributor-management-service
  template:
    metadata:
      labels:
        app: contributor-management-service
    spec:
      containers:
        - name: contributor-management-service
          image: gcr.io/developer-iq-tracker/contributor-management-service:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /api/v1/contributor-management-service/actuator/health
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 8080
              path: /api/v1/contributor-management-service/actuator/health
            initialDelaySeconds: 40
            periodSeconds: 10
          resources:
            requests:
              cpu: "300m"
              memory: "400Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"